apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ModernShop-secrets
  namespace: dapr-ModernShop
spec:
  type: secretstores.local.file
  version: v1  
  metadata:
  - name: secretsFile
    value: ../../dapr/components/secrets.json
  - name: nestedSeparator
    value: "."
scopes:
  - catalogservice
  - identityservice
  